name: Differences Experiment

on:
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r differences_experiment/requirements.txt
      - name: Generate charts
        run: |
          python differences_experiment/largest_cities_differences.py
