name: Differences Experiment

on:
  workflow_dispatch:

permissions:
  contents: write


jobs:
  run-experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r differences_experiment/requirements.txt
      - name: Run tests
        run: |
          pytest differences_experiment
      - name: Generate charts
        run: |
          python differences_experiment/largest_cities_differences.py
      - name: Commit charts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f differences_experiment/*.png
          git commit -m "Add generated charts" || echo "No changes to commit"
          git push
